# Face tags for cylinder flow

[[FaceTag]]
# Left face
marker = 1
when = { axis = "x", equals = 0.0 }

[[FaceTag]]
# Right face
marker = 2
when = { axis = "x", equals = 4.4 }

[[FaceTag]]
# Bottom face
marker = 3
when = { axis = "y", equals = 0.0 }

[[FaceTag]]
# Top face
marker = 4
when = { axis = "y", equals = 3.3 }

[[FaceTag]]
# Fallback for unmatched surfaces (e.g, cylinder)
marker = 5
otherwise = true
