[[BC]]
# Inlet
marker = 1
type = "dirichlet_velocity"
value = [1.0, 0.0]

[[BC]]
# Outlet
marker = 2
type = "neumann_velocity"
value = [0.0, 0.0]

[[BC]]
# Free-flow
marker = 3
type = "neumann_velocity"
value = [0.0, 0.0]

[[BC]]
# Free-flow
marker = 4
type = "neumann_velocity"
value = [0.0, 0.0]

[[BC]]
# Wall
marker = 5
type = "dirichlet_velocity"
value = [0.0, 0.0]