# Facet tags for cylinder flow

[[FaceTag]]
# Inlet
marker = 1
when = { axis = "x", equals = -20.0 }

[[FaceTag]]
# Outlet
marker = 2
when = { axis = "x", equals = 80.0 }

[[FaceTag]]
# Bottom
marker = 3
when = { axis = "y", equals = -15.0 }

[[FaceTag]]
# Top
marker = 4
when = { axis = "y", equals = 15.0 }

[[FaceTag]]
# Fallback for unmatched surfaces (e.g, cylinder)
marker = 5
otherwise = true