dim = 2
cylinder_radius = 0.5
cylinder_center = [0.0, 0.0]
x_range = [-20.0, 80.0]
y_range = [-20.0, 20.0]
resolution = 0.75
resolution_around_cylinder = 0.10
influence_radius = 40
influence_length = 40