[[FaceTag]]
# Left face (x = 0)
marker = 1
when = { axis = "x", equals = 0.0 }

[[FaceTag]]
# Right face (x = 1)
marker = 2
when = { axis = "x", equals = 1.0 }

[[FaceTag]]
# Bottom face (y = 0)
marker = 3
when = { axis = "y", equals = 0.0 }

[[FaceTag]]
# Top face (y = 1)
marker = 4
when = { axis = "y", equals = 1.0 }

[[FaceTag]]
# Back face (z = 0)
marker = 5
when = { axis = "z", equals = 0.0 }

[[FaceTag]]
# Front face (z = 1)
marker = 6
when = { axis = "z", equals = 1.0 }

[[FaceTag]]
# Fallback for unmatched surfaces (should not happen on unit box)
marker = 99
otherwise = true
